--Certificado_Competencias_
SELECT DISTINCT C.SMBPOGN_COLL_CODE AS FACULTAD, C.SMBAOGN_PROGRAM AS PROGRAMA, C.SMBAOGN_TERM_CODE_EFF AS PERIODO_CATALOGO, C.SMBPOGN_CAMP_CODE AS CAMPUS, SMRACMT_TEXT AS CERTIFICADO	--, SMBAOGN_PIDM
	, C.SPRIDEN_ID AS ID_ESTUDIANTE, C.SPRIDEN_LAST_NAME ||', '|| C.SPRIDEN_FIRST_NAME AS ESTUDIANTE
	--, C.SMBAOGN_REQUEST_NO AS SOLICITUD, C.SMBPOGN_ACTIVITY_DATE, C.SMRDOUS_COMPLIANCE_ORDER AS ITEM
	, ROW_NUMBER() OVER(PARTITION BY C.SMBAOGN_PROGRAM, C.SMBAOGN_TERM_CODE_EFF, C.SMBAOGN_PIDM ORDER BY C.SMRDOUS_TERM_CODE/*, C.SMRDOUS_COMPLIANCE_ORDER*/) AS ITEM
	, SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW ||' - '|| SCBCRSE_TITLE AS CURSO_CERTIFICACION
	, C.SMRDOUS_SUBJ_CODE || C.SMRDOUS_CRSE_NUMB ||' - '|| C.SMRDOUS_TITLE AS CURSO_APROBADO
	, CASE 
		WHEN SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = C.SMRDOUS_SUBJ_CODE||C.SMRDOUS_CRSE_NUMB AND SUBSTR(C.SMRDOUS_GRDE_CODE,1,1) = 'C' THEN 'EL MISMO CURSO, CONVALIDADO'
		WHEN SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = C.SMRDOUS_SUBJ_CODE||C.SMRDOUS_CRSE_NUMB THEN 'EL MISMO CURSO'
		WHEN SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = C.SCREQIV_SUBJ_CODE_EQIV||C.SCREQIV_CRSE_NUMB_EQIV AND SUBSTR(C.SMRDOUS_GRDE_CODE,1,1) = 'C' THEN 'CURSO EQUIVALENTE, CONVALIDADO'
		WHEN SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = C.SCREQIV_SUBJ_CODE_EQIV||C.SCREQIV_CRSE_NUMB_EQIV THEN 'CURSO EQUIVALENTE'
		WHEN SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = C.SMRSSUB_SUBJ_CODE_REQ||C.SMRSSUB_CRSE_NUMB_REQ AND SUBSTR(C.SMRDOUS_GRDE_CODE,1,1) = 'C' THEN 'CURSO SUSTITUTO, CONVALIDADO'
		WHEN SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = C.SMRSSUB_SUBJ_CODE_REQ||C.SMRSSUB_CRSE_NUMB_REQ THEN 'CURSO SUSTITUTO'
		ELSE 'CURSO CUMPLIDO POR AJUSTE DE CAPP' END AS REFERENCIA
	, C.SMRDOUS_GRDE_CODE AS NOTA, C.SMRDOUS_TERM_CODE AS SEMESTRE, SPRHOLD_HLDD_CODE AS RETENCION
FROM ( SELECT DISTINCT SMBPOGN_COLL_CODE, SMBAOGN_PROGRAM, SMBAOGN_TERM_CODE_EFF, SMBPOGN_CAMP_CODE, SMBAOGN_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME, SPRIDEN_FIRST_NAME, SMBAOGN_REQUEST_NO
			, SMBPOGN_ACTIVITY_DATE, SMBAOGN_AREA, SMRDOUS_COMPLIANCE_ORDER, SMRDOUS_SUBJ_CODE, SMRDOUS_CRSE_NUMB, SMRDOUS_TITLE, SMRDOUS_GRDE_CODE, SMRDOUS_TERM_CODE
			, MIN(SMRDOUS_TERM_CODE) OVER(PARTITION BY SMRDOUS_PIDM, SMRDOUS_REQUEST_NO, SMRDOUS_AREA) AS MIN_SMRDOUS_TERM_CODE
			, MAX(SMRDOUS_TERM_CODE) OVER(PARTITION BY SMRDOUS_PIDM, SMRDOUS_REQUEST_NO, SMRDOUS_AREA) AS MAX_SMRDOUS_TERM_CODE
			, SCREQIV_SUBJ_CODE_EQIV, SCREQIV_CRSE_NUMB_EQIV, SMRSSUB_SUBJ_CODE_REQ, SMRSSUB_CRSE_NUMB_REQ
		FROM SMBAOGN A
				INNER JOIN SMRDOUS ON SMBAOGN_PIDM = SMRDOUS_PIDM AND SMBAOGN_REQUEST_NO = SMRDOUS_REQUEST_NO AND SMBAOGN_AREA = SMRDOUS_AREA
				INNER JOIN SMBPOGN B ON SMBAOGN_PIDM = SMBPOGN_PIDM AND SMBAOGN_REQUEST_NO = SMBPOGN_REQUEST_NO
										AND B.SMBPOGN_REQUEST_NO = (SELECT MAX(B1.SMBPOGN_REQUEST_NO) FROM SMBPOGN B1
																	WHERE B1.SMBPOGN_PIDM = B.SMBPOGN_PIDM AND B1.SMBPOGN_PROGRAM = B.SMBPOGN_PROGRAM)
				INNER JOIN SPRIDEN ON SMBAOGN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
				LEFT JOIN ( SELECT SMRACAA_AREA, SMRACAA_TERM_CODE_EFF, SCREQIV_SUBJ_CODE, SCREQIV_CRSE_NUMB, SCREQIV_SUBJ_CODE_EQIV, SCREQIV_CRSE_NUMB_EQIV
							FROM SMRACAA, SCREQIV
							WHERE SMRACAA_SUBJ_CODE = SCREQIV_SUBJ_CODE_EQIV AND SMRACAA_CRSE_NUMB_LOW = SCREQIV_CRSE_NUMB_EQIV
								AND SMRACAA_TERM_CODE_EFF BETWEEN SCREQIV_START_TERM AND SCREQIV_END_TERM AND SMRACAA_AREA LIKE '%-CERT'
							) E ON SMRDOUS_SUBJ_CODE = SCREQIV_SUBJ_CODE AND SMRDOUS_CRSE_NUMB = SCREQIV_CRSE_NUMB AND SMRDOUS_AREA = SMRACAA_AREA AND SMRDOUS_TERM_CODE_EFF = SMRACAA_TERM_CODE_EFF
				LEFT JOIN SMRSSUB ON SMRDOUS_PIDM = SMRSSUB_PIDM AND SMRDOUS_SUBJ_CODE = SMRSSUB_SUBJ_CODE_SUB AND SMRDOUS_CRSE_NUMB = SMRSSUB_CRSE_NUMB_SUB
		WHERE SMBAOGN_MET_IND = 'Y' AND SMBAOGN_AREA LIKE '%-CERT'
			AND A.SMBAOGN_REQUEST_NO = (SELECT MAX(A1.SMBAOGN_REQUEST_NO) FROM SMBAOGN A1
										WHERE A1.SMBAOGN_PIDM = A.SMBAOGN_PIDM AND A1.SMBAOGN_PROGRAM = A.SMBAOGN_PROGRAM AND A1.SMBAOGN_AREA LIKE '%-CERT')
	)C
		LEFT JOIN SMRACAA ON C.SMBAOGN_AREA = SMRACAA_AREA AND C.SMBAOGN_TERM_CODE_EFF = SMRACAA_TERM_CODE_EFF
							AND (C.SMRDOUS_SUBJ_CODE||C.SMRDOUS_CRSE_NUMB = SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW
									OR C.SCREQIV_SUBJ_CODE_EQIV||C.SCREQIV_CRSE_NUMB_EQIV = SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW
									OR C.SMRSSUB_SUBJ_CODE_REQ||C.SMRSSUB_CRSE_NUMB_REQ = SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW)
		LEFT JOIN SCBCRSE D ON SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = SCBCRSE_SUBJ_CODE||SCBCRSE_CRSE_NUMB
							AND D.SCBCRSE_EFF_TERM = (SELECT MAX(D1.SCBCRSE_EFF_TERM) FROM SCBCRSE D1
														WHERE D1.SCBCRSE_SUBJ_CODE||D1.SCBCRSE_CRSE_NUMB = SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW AND D1.SCBCRSE_EFF_TERM <= SMRACAA_TERM_CODE_EFF)
		LEFT JOIN SMRACMT ON C.SMBAOGN_AREA = SMRACMT_AREA AND C.SMBAOGN_TERM_CODE_EFF = SMRACMT_TERM_CODE_EFF AND SMRACMT_PRNT_CODE = 'LNAME1'
		LEFT JOIN SPRHOLD ON C.SMBAOGN_PIDM = SPRHOLD_PIDM AND SPRHOLD_HLDD_CODE = 'SD' AND SYSDATE BETWEEN SPRHOLD_FROM_DATE AND SPRHOLD_TO_DATE
WHERE (SUBSTR(C.MIN_SMRDOUS_TERM_CODE,4,1) = 4 AND C.MIN_SMRDOUS_TERM_CODE >= '218434') OR (SUBSTR(C.MIN_SMRDOUS_TERM_CODE,4,1) = 5 AND C.MIN_SMRDOUS_TERM_CODE >= '218533')
	--AND C.MAX_SMRDOUS_TERM_CODE IN ('220413','220513')	--INGRESAR_PERIODO
ORDER BY C.SMBAOGN_PROGRAM, C.SMBAOGN_TERM_CODE_EFF, C.SMBPOGN_CAMP_CODE, C.SPRIDEN_ID
;

SELECT * FROM SMRACAA
WHERE SMRACAA_AREA LIKE '%-CERT'
;

SELECT *--DISTINCT SMBAOGN_AREA
FROM SMBAOGN LEFT JOIN SMRDOUS ON SMBAOGN_PIDM = SMRDOUS_PIDM AND SMBAOGN_REQUEST_NO = SMRDOUS_REQUEST_NO AND SMBAOGN_AREA = SMRDOUS_AREA
WHERE SMBAOGN_AREA LIKE '%-CERT'
;