--Certificado_Competencias_
SELECT SMBPOGN_COLL_CODE AS FACULTAD, SMBAOGN_PROGRAM AS PROGRAMA, SMBAOGN_TERM_CODE_EFF AS PERIODO_CATALOGO, SMBPOGN_CAMP_CODE AS CAMPUS--, SMBAOGN_PIDM
	, SPRIDEN_ID AS ID_ESTUDIANTE, SPRIDEN_LAST_NAME ||', '|| SPRIDEN_FIRST_NAME AS ESTUDIANTE
	--, SMBAOGN_REQUEST_NO AS SOLICITUD, SMBPOGN_ACTIVITY_DATE, SMRDOUS_COMPLIANCE_ORDER AS ITEM
	, ROW_NUMBER() OVER(PARTITION BY SMBAOGN_PROGRAM, SMBAOGN_TERM_CODE_EFF, SMBAOGN_PIDM ORDER BY SMRDOUS_TERM_CODE, SMRDOUS_COMPLIANCE_ORDER) AS ITEM
	, CASE WHEN SMRACAA_RULE IS NULL THEN SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW ELSE SMRACAA_RULE END ||' - '|| SCBCRSE_TITLE AS CURSO_CERTIFICACION
	, SMRDOUS_SUBJ_CODE || SMRDOUS_CRSE_NUMB ||' - '|| SMRDOUS_TITLE AS CURSO_APROBADO
	, CASE 
		WHEN (SMRACAA_RULE = SMRDOUS_SUBJ_CODE||SMRDOUS_CRSE_NUMB OR SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = SMRDOUS_SUBJ_CODE||SMRDOUS_CRSE_NUMB) AND SUBSTR(SMRDOUS_GRDE_CODE,1,1) = 'C' THEN 'EL MISMO CURSO, CONVALIDADO'
		WHEN (SMRACAA_RULE = SMRDOUS_SUBJ_CODE||SMRDOUS_CRSE_NUMB OR SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = SMRDOUS_SUBJ_CODE||SMRDOUS_CRSE_NUMB) THEN 'EL MISMO CURSO'
		WHEN (SMRACAA_RULE = SMRSSUB_SUBJ_CODE_REQ||SMRSSUB_CRSE_NUMB_REQ OR SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = SMRSSUB_SUBJ_CODE_REQ||SMRSSUB_CRSE_NUMB_REQ) AND SUBSTR(SMRDOUS_GRDE_CODE,1,1) = 'C' THEN 'CURSO EQUIVALENTE, CONVALIDADO'
		WHEN (SMRACAA_RULE = SMRSSUB_SUBJ_CODE_REQ||SMRSSUB_CRSE_NUMB_REQ OR SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = SMRSSUB_SUBJ_CODE_REQ||SMRSSUB_CRSE_NUMB_REQ) THEN 'CURSO EQUIVALENTE'
		ELSE 'CURSO CUMPLIDO POR AJUSTE DE CAPP' END AS REFERENCIA
	, SMRDOUS_GRDE_CODE AS NOTA, SMRDOUS_TERM_CODE AS SEMESTRE
	--, SMRSSUB_SUBJ_CODE_REQ || SMRSSUB_CRSE_NUMB_REQ AS CURSO_SUSTITUTO
FROM ( SELECT SMBPOGN_COLL_CODE, SMBAOGN_PROGRAM, SMBAOGN_TERM_CODE_EFF, SMBPOGN_CAMP_CODE, SMBAOGN_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME, SPRIDEN_FIRST_NAME
			, SMBAOGN_REQUEST_NO, SMBPOGN_ACTIVITY_DATE, SMBAOGN_AREA, SMRDOUS_COMPLIANCE_ORDER, SMRDOUS_SUBJ_CODE, SMRDOUS_CRSE_NUMB, SMRDOUS_TITLE
			, SMRDOUS_GRDE_CODE, SMRDOUS_TERM_CODE, MIN(SMRDOUS_TERM_CODE) AS MIN_SMRDOUS_TERM_CODE, SMRSSUB_SUBJ_CODE_REQ, SMRSSUB_CRSE_NUMB_REQ
		FROM SMBAOGN A
				INNER JOIN SMRDOUS ON SMBAOGN_PIDM = SMRDOUS_PIDM AND SMBAOGN_REQUEST_NO = SMRDOUS_REQUEST_NO AND SMBAOGN_AREA = SMRDOUS_AREA
				INNER JOIN SMBPOGN B ON SMBAOGN_PIDM = SMBPOGN_PIDM AND SMBAOGN_REQUEST_NO = SMBPOGN_REQUEST_NO
										AND B.SMBPOGN_REQUEST_NO = (SELECT MAX(B1.SMBPOGN_REQUEST_NO) FROM SMBPOGN B1
																	WHERE B1.SMBPOGN_PIDM = B.SMBPOGN_PIDM AND B1.SMBPOGN_PROGRAM = B.SMBPOGN_PROGRAM)
				INNER JOIN SPRIDEN ON SMBAOGN_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
				LEFT JOIN SMRSSUB ON SMBAOGN_PIDM = SMRSSUB_PIDM AND SMRDOUS_SUBJ_CODE = SMRSSUB_SUBJ_CODE_SUB AND SMRDOUS_CRSE_NUMB = SMRSSUB_CRSE_NUMB_SUB
		WHERE /*SMBAOGN_MET_IND = 'Y' AND*/ SMBAOGN_AREA LIKE '%-CERT'
			AND A.SMBAOGN_REQUEST_NO = (SELECT MAX(A1.SMBAOGN_REQUEST_NO) FROM SMBAOGN A1
										WHERE A1.SMBAOGN_PIDM = A.SMBAOGN_PIDM AND A1.SMBAOGN_PROGRAM = A.SMBAOGN_PROGRAM AND A1.SMBAOGN_AREA LIKE '%-CERT')
		GROUP BY SMBPOGN_COLL_CODE, SMBAOGN_PROGRAM, SMBAOGN_TERM_CODE_EFF, SMBPOGN_CAMP_CODE, SMBAOGN_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME, SPRIDEN_FIRST_NAME
			, SMBAOGN_REQUEST_NO, SMBPOGN_ACTIVITY_DATE, SMBAOGN_AREA, SMRDOUS_COMPLIANCE_ORDER, SMRDOUS_SUBJ_CODE, SMRDOUS_CRSE_NUMB, SMRDOUS_TITLE
			, SMRDOUS_GRDE_CODE, SMRDOUS_TERM_CODE, SMRSSUB_SUBJ_CODE_REQ, SMRSSUB_CRSE_NUMB_REQ
	)C
		LEFT JOIN SMRACAA ON C.SMBAOGN_AREA = SMRACAA_AREA AND C.SMBAOGN_TERM_CODE_EFF = SMRACAA_TERM_CODE_EFF
							AND (SMRDOUS_SUBJ_CODE||SMRDOUS_CRSE_NUMB = SMRACAA_RULE OR SMRDOUS_SUBJ_CODE||SMRDOUS_CRSE_NUMB = SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW
								OR SMRSSUB_SUBJ_CODE_REQ||SMRSSUB_CRSE_NUMB_REQ = SMRACAA_RULE OR SMRSSUB_SUBJ_CODE_REQ||SMRSSUB_CRSE_NUMB_REQ = SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW)
		LEFT JOIN SCBCRSE ON (SMRACAA_RULE = SCBCRSE_SUBJ_CODE||SCBCRSE_CRSE_NUMB OR SMRACAA_SUBJ_CODE||SMRACAA_CRSE_NUMB_LOW = SCBCRSE_SUBJ_CODE||SCBCRSE_CRSE_NUMB)
							AND SMRACAA_TERM_CODE_EFF = SCBCRSE_EFF_TERM
WHERE (SUBSTR(MIN_SMRDOUS_TERM_CODE,4,1) = 4 AND MIN_SMRDOUS_TERM_CODE >= '218434') OR (SUBSTR(MIN_SMRDOUS_TERM_CODE,4,1) = 5 AND MIN_SMRDOUS_TERM_CODE >= '218533')
;

SELECT * FROM SMRACAA
WHERE SMRACAA_AREA LIKE '%-CERT'
;

SELECT *--DISTINCT SMBAOGN_AREA
FROM SMBAOGN LEFT JOIN SMRDOUS ON SMBAOGN_PIDM = SMRDOUS_PIDM AND SMBAOGN_REQUEST_NO = SMRDOUS_REQUEST_NO AND SMBAOGN_AREA = SMRDOUS_AREA
WHERE SMBAOGN_AREA LIKE '%-CERT'
;
