--Matriculas_Mismo_Curso
SELECT D.SFRSTCR_PIDM, SPRIDEN_ID, SPRIDEN_LAST_NAME ||', '|| SPRIDEN_FIRST_NAME AS ESTUDIANTE, D.SFRSTCR_TERM_CODE
	, D.SSBSECT_SUBJ_CODE, D.SSBSECT_CRSE_NUMB, B.SFRSTCR_CRN, B.SFRSTCR_RSTS_CODE, B.SFRSTCR_RSTS_DATE, B.SFRSTCR_USER
FROM (
	SELECT SFRSTCR_PIDM, SFRSTCR_TERM_CODE, SSBSECT_SUBJ_CODE, SSBSECT_CRSE_NUMB
	FROM SFRSTCR
			INNER JOIN SSBSECT ON SFRSTCR_TERM_CODE = SSBSECT_TERM_CODE AND SFRSTCR_CRN = SSBSECT_CRN
	WHERE SFRSTCR_TERM_CODE IN ('220435','220534') AND SFRSTCR_RSTS_CODE IN ('RE','RW','RA')
	GROUP BY SFRSTCR_PIDM, SFRSTCR_TERM_CODE, SSBSECT_SUBJ_CODE, SSBSECT_CRSE_NUMB
	HAVING COUNT(SFRSTCR_CRN) > 1
	) D
		INNER JOIN SSBSECT A ON D.SFRSTCR_TERM_CODE = A.SSBSECT_TERM_CODE AND D.SSBSECT_SUBJ_CODE = A.SSBSECT_SUBJ_CODE AND D.SSBSECT_CRSE_NUMB = A.SSBSECT_CRSE_NUMB
		INNER JOIN SFRSTCR B ON D.SFRSTCR_PIDM = B.SFRSTCR_PIDM AND D.SFRSTCR_TERM_CODE = B.SFRSTCR_TERM_CODE AND A.SSBSECT_CRN = B.SFRSTCR_CRN AND B.SFRSTCR_RSTS_CODE IN ('RE','RW','RA')
		INNER JOIN SPRIDEN ON D.SFRSTCR_PIDM = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
ORDER BY D.SFRSTCR_PIDM, D.SFRSTCR_TERM_CODE, D.SSBSECT_SUBJ_CODE, D.SSBSECT_CRSE_NUMB, B.SFRSTCR_CRN
;