SELECT DISTINCT 
    :1
    --, TBRACCD_PIDM
    , TBRACCD_TRAN_NUMBER
    , TBRACCD_SURROGATE_ID
FROM TBRACCD
WHERE TBRACCD_PIDM = gb_common.f_get_pidm(:1)  --ID
    AND TBRACCD_TRAN_NUMBER IN (17,18,19);
