SELECT DISTINCT 
    GB_COMMON.F_GET_ID(TBRACCD_PIDM)
    --, TBRACCD_PIDM
    , TBRACCD_TRAN_NUMBER
    , TBRACCD_SURROGATE_ID
FROM TBRACCD
WHERE GB_COMMON.F_GET_ID(TBRACCD_PIDM) = 'N00048528'    --ID
    AND TBRACCD_TRAN_NUMBER IN (17,18,19);
