SELECT DISTINCT 
    GB_COMMON.F_GET_ID(TBRACCD_PIDM)
    --, TBRACCD_PIDM
    , TBRACCD_TRAN_NUMBER
    , TBRACCD_SURROGATE_ID
FROM TBRACCD
WHERE TBRACCD_PIDM = GB_COMMON.F_GET_PIDM('N00261078')  --ID
    --AND TBRACCD_TRAN_NUMBER IN (17,18,19);
    AND TBRACCD_TRAN_NUMBER >= 1 AND TBRACCD_TRAN_NUMBER <= 38;
