--Validar_SCBCRSE_DS_
SELECT SUBSTR(A.GORSDAV_VALUE.ACCESSNUMBER(),1,6) AS PERIODO, CASE SUBSTR(A.GORSDAV_VALUE.ACCESSNUMBER(),4,1) WHEN '4' THEN 'UG' WHEN '5' THEN 'WA' ELSE NULL END AS MODALIDAD
	, SUBSTR(GORSDAV_PK_PARENTTAB,1,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)-1) || SUBSTR(GORSDAV_PK_PARENTTAB,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)+1,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),-1)-INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)-1) AS COD_CURSO
	, SCBCRSE_TITLE AS CURSO, CAST(SUBSTR(A.GORSDAV_VALUE.ACCESSNUMBER(),7) AS INT) AS TOPE, GORSDAV_ACTIVITY_DATE
FROM GORSDAV A
		LEFT JOIN SCBCRSE ON SUBSTR(GORSDAV_PK_PARENTTAB,1,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)-1) = SCBCRSE_SUBJ_CODE
								AND SUBSTR(GORSDAV_PK_PARENTTAB,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)+1,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),-1)-INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)-1) = SCBCRSE_CRSE_NUMB
								AND SUBSTR(GORSDAV_PK_PARENTTAB,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),-1)+1) = SCBCRSE_EFF_TERM
WHERE GORSDAV_TABLE_NAME = 'SCBCRSE' AND SUBSTR(A.GORSDAV_VALUE.ACCESSNUMBER(),1,6) IN ('221413','221513')
ORDER BY GORSDAV_ACTIVITY_DATE DESC
;
