--Validar_SCRSYLN_NombreCurso_
SELECT SCBCRSE_SUBJ_CODE, SCBCRSE_CRSE_NUMB, SCBCRSE_EFF_TERM, SCBCRSE_COLL_CODE, SCBCRSE_DEPT_CODE, SCBCRSE_CSTA_CODE
	, SCBCRSE_TITLE, SCBCRSE_ACTIVITY_DATE--, A.SCRSYLN_TERM_CODE_EFF, A.SCRSYLN_LONG_COURSE_TITLE, A.SCRSYLN_ACTIVITY_DATE
FROM SCBCRSE
		LEFT JOIN SCRSYLN A ON SCBCRSE_SUBJ_CODE = A.SCRSYLN_SUBJ_CODE AND SCBCRSE_CRSE_NUMB = A.SCRSYLN_CRSE_NUMB
								AND SCBCRSE_EFF_TERM < A.SCRSYLN_TERM_CODE_EFF
		LEFT JOIN SCRSYLN B ON SCBCRSE_SUBJ_CODE = B.SCRSYLN_SUBJ_CODE AND SCBCRSE_CRSE_NUMB = B.SCRSYLN_CRSE_NUMB
								AND SCBCRSE_EFF_TERM >= B.SCRSYLN_TERM_CODE_EFF
WHERE B.SCRSYLN_SUBJ_CODE IS NULL --AND SCBCRSE_ACTIVITY_DATE > TO_DATE('2020-01-01','YYYY-MM-DD')
	AND SCBCRSE_SUBJ_CODE NOT IN ('ACAD','REPS','TEST','XPEN','XSER') AND SCBCRSE_SUBJ_CODE NOT IN ('REFO') --reforzamiento
	AND SCBCRSE_DEPT_CODE <> 'EPEC'
	--AND SCBCRSE_DEPT_CODE = 'EPEC'
	--AND SCBCRSE_SUBJ_CODE || SCBCRSE_CRSE_NUMB IN ('IELE9924','IELE9925','INDU9924','MAGM9948', 'IELE9929','IELE9930','ITEC9922','INDU9923','SIST9947')
	--AND SCBCRSE_SUBJ_CODE || SCBCRSE_CRSE_NUMB IN ('INVE1586')
	AND A.SCRSYLN_SUBJ_CODE IS NULL
ORDER BY SCBCRSE_ACTIVITY_DATE DESC
;
--Inhabilitados_
SELECT SCBCRSE_COLL_CODE, SCBCRSE_DEPT_CODE, SCBCRSE_ACTIVITY_DATE, SCBCRSE_EFF_TERM
	, SCBCRSE_SUBJ_CODE, SCBCRSE_CRSE_NUMB, B.SCRSYLN_LONG_COURSE_TITLE, SCBCRSE_CSTA_CODE
FROM SCBCRSE
		LEFT JOIN SCRSYLN A ON SCBCRSE_SUBJ_CODE = A.SCRSYLN_SUBJ_CODE AND SCBCRSE_CRSE_NUMB = A.SCRSYLN_CRSE_NUMB
								AND SCBCRSE_EFF_TERM < A.SCRSYLN_TERM_CODE_EFF
		LEFT JOIN SCRSYLN B ON SCBCRSE_SUBJ_CODE = B.SCRSYLN_SUBJ_CODE AND SCBCRSE_CRSE_NUMB = B.SCRSYLN_CRSE_NUMB
								AND SCBCRSE_EFF_TERM >= B.SCRSYLN_TERM_CODE_EFF
WHERE 
	--SCBCRSE_SUBJ_CODE || SCBCRSE_CRSE_NUMB IN ('IELE9924','IELE9925','INDU9924','MAGM9948', 'IELE9929','IELE9930','ITEC9922','INDU9923','SIST9947')
	SCBCRSE_SUBJ_CODE || SCBCRSE_CRSE_NUMB IN ('INVE9926'
,'REPR9935'
,'CARQ9924'
,'CARQ9928'
,'TPRO9920'
,'CARQ9925'
,'CARQ9943'
,'CARQ9945'
,'TPRO9921'
,'CARQ9926'
,'CARQ9946')
ORDER BY SCBCRSE_ACTIVITY_DATE DESC
;
