--Validar_SHRQPNM_DS_
SELECT SUBSTR(GORSDAV_PK_PARENTTAB,1,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)-1) AS DECODE_PIDM, SPRIDEN_ID, SPRIDEN_FIRST_NAME ||' '|| REPLACE(SPRIDEN_LAST_NAME,'/',' ') AS NOMBRE_ESTUDIANTE
	, SUBSTR(GORSDAV_PK_PARENTTAB,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)+1) DECODE_SEQ, SHRQPNM_QPTP_CODE, SHRQPNM_ACCP_DATE AS FECHA_CONVOCATORIA, SHRQPNM_TITLE_LINE1, SHRQPNM_TITLE_LINE2, GORSDAV_PK_PARENTTAB, GORSDAV_USER_ID
	, MAX(GORSDAV_ACTIVITY_DATE) AS FECHA_CARGA
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'TESIS' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS TESIS
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'URL_TESIS' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS URL_TESIS
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'ACTO_TIP' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS ACTO_TIP
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'MODALIDAD' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS MODALIDAD
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'RESO_NUM' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS RESO_NUM
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'RESO_FEC' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS RESO_FEC
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'DIPL_NUM' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS DIPL_NUM
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'DIPL_FEC' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS DIPL_FEC
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'DIPL_TIP_EMI' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS DIPL_TIP_EMI
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'REG_LIBRO' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS REG_LIBRO
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'REG_FOLIO' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS REG_FOLIO
	, MAX(CASE WHEN GORSDAV_ATTR_NAME = 'REG_REGISTRO' THEN A.GORSDAV_VALUE.ACCESSVARCHAR2() END) AS REG_REGISTRO
FROM GORSDAV A
		INNER JOIN SPRIDEN ON SUBSTR(GORSDAV_PK_PARENTTAB,1,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)-1) = SPRIDEN_PIDM AND SPRIDEN_CHANGE_IND IS NULL
		LEFT JOIN SHRQPNM ON SUBSTR(GORSDAV_PK_PARENTTAB,1,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)-1) = SHRQPNM_PIDM AND SUBSTR(GORSDAV_PK_PARENTTAB,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)+1) = SHRQPNM_SEQ_NO
WHERE GORSDAV_ATTR_NAME IN ('TESIS','URL_TESIS','ACTO_TIP','MODALIDAD','RESO_NUM','RESO_FEC','DIPL_NUM','DIPL_FEC','DIPL_TIP_EMI','REG_LIBRO','REG_FOLIO','REG_REGISTRO')
	AND GORSDAV_TABLE_NAME = 'SHRQPNM' AND GORSDAV_USER_ID = 'S200014252' --USUARIO_CARGA
	AND GORSDAV_ACTIVITY_DATE BETWEEN TO_DATE('10/09/2020','DD/MM/YYYY') AND TO_DATE('10/09/2020','DD/MM/YYYY') --FECHA_CARGA
	--AND SHRQPNM_ACCP_DATE BETWEEN TO_DATE('22/06/2020','DD/MM/YYYY') AND TO_DATE('10/07/2020','DD/MM/YYYY') --FECHA_CONVOCATORIA
	--AND SUBSTR(GORSDAV_PK_PARENTTAB,1,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)-1) IN (68264)
GROUP BY SUBSTR(GORSDAV_PK_PARENTTAB,1,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)-1), SPRIDEN_ID, SPRIDEN_FIRST_NAME ||' '|| REPLACE(SPRIDEN_LAST_NAME,'/',' ')
	, SUBSTR(GORSDAV_PK_PARENTTAB,INSTR(GORSDAV_PK_PARENTTAB,CHR(1),1)+1), SHRQPNM_QPTP_CODE, SHRQPNM_ACCP_DATE, SHRQPNM_TITLE_LINE1, SHRQPNM_TITLE_LINE2, GORSDAV_PK_PARENTTAB, GORSDAV_USER_ID
;

--Validar - Saltos de linea en GORSDAV_VALUE
SELECT A.GORSDAV_VALUE.ACCESSVARCHAR2(), A.* FROM GORSDAV A WHERE SUBSTR(A.GORSDAV_VALUE.ACCESSVARCHAR2(),1,1) LIKE '%'||CHR(10)||'%';
